### ISSUE TITLE
Add brandonwillard as maintainer

### ISSUE THREAD

**Issue by twiecki** [conda-forge/theano-pymc-feedstock#9]
Can an admin add @brandonwillard as a maintainer with write/merge access to this repo? Thanks!

**Comment by brandonwillard** [comment]
@ericmjl, are you the maintainer here?

**Comment by ericmjl** [comment]
@brandonwillard yep! You can add yourself in via a PR that modifies the build recipe, in `recipes/meta.yaml`. Please add yourself at the end of [this file](https://github.com/conda-forge/theano-pymc-feedstock/blob/master/recipe/meta.yaml). (I'm having you do it, as it's helpful for maintainers to be involved in the workflow.)

I'm not a maintainer of the repo; the conda-forge team is. However, we self-select as maintainers of the feedstock by doing PRs to add ourselves as maintainers on the build recipe.

**Comment by brandonwillard** [comment]
Ah, I see; will do.
